from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class LeaderboardProvider(Protocol):
    """Protocol for leaderboard data provider."""

    def get_catalog(self) -> list[dict[str, Any]] | None: ...
    def get_latest_text_by_source(self, source_key: str) -> dict[str, Any] | None: ...
    def get_texts_by_source(self, source_key: str) -> list[dict[str, Any]] | None: ...
    def get_text_by_id(self, text_id: int) -> dict[str, Any] | None: ...
    def get_leaderboard(
        self, text_id: int, page: int = 1, size: int = 50
    ) -> dict[str, Any] | None: ...
